checking multiple files, too

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -21,20 +21,20 @@ jobs:
     - name: Upload
       uses: ./
       with:
-        name: "Single-File-${{ matrix.runs-on }}"
+        name: single-file-${{ matrix.runs-on }}
         path: __testFiles__/DirA/SubDirA/FileAA.md
         retention-days: 1
     - name: Upload Comparison
       uses: actions/upload-artifact@v3
       with:
-        name: Comparison
+        name: comparison-single-${{ matrix.runs-on }}
         retention-days: 1
         path: __testFiles__/DirA/SubDirA/FileAA.md
         if-no-files-found: error
     - name: Download Archive
       uses: actions/download-artifact@v3
       with:
-        name: "Single-File-${{ matrix.runs-on }}"
+        name: single-file-${{ matrix.runs-on }}
         path: check
     - name: Check Archive Exists
       run: |
@@ -52,4 +52,47 @@ jobs:
           echo "Missing archive contents!"
           exit 1
         fi
+      working-directory: check
+
+  multi-file-upload:
+    name: Multiple Files Upload Test
+    strategy:
+      matrix:
+        runs-on: [ubuntu-latest, macos-latest]
+      fail-fast: false
+    runs-on: ${{ matrix.runs-on }}
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v2
+    - name: Upload
+      uses: ./
+      with:
+        name: multiple-files-${{ matrix.runs-on }}
+        path: __testFiles__/**
+        retention-days: 1
+    - name: Upload Comparison
+      uses: actions/upload-artifact@v3
+      with:
+        name: comparison-multiple-${{ matrix.runs-on }}
+        retention-days: 1
+        path: __testFiles__/**
+        if-no-files-found: error
+    - name: Download Archive
+      uses: actions/download-artifact@v3
+      with:
+        name: multiple-files-${{ matrix.runs-on }}
+        path: check
+    - name: Check Archive Exists
+      run: |
+        count=$(ls -1 *.rTmpArchive.zip 2>/dev/null | wc -l)
+        if [ $count != 1 ]; then
+          echo "Missing archive file!"
+          exit 1
+        fi
+      working-directory: check
+    - name: Check Archive contents
+      run: |
+        unzip *.rTmpArchive.zip -d ./tmp
+
+        diff __testFiles__ tmp
       working-directory: check
